# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the mu vector of means of a Gaussian linear network
#' 
#' @param fit a bn.fit object
#' @param order a topological ordering of the nodes
#' @return the numeric named vector of means
#' @export
calc_mu <- function(fit, order) {
    .Call('_dbnR_calc_mu', PACKAGE = 'dbnR', fit, order)
}

